version: '3.8'

services:
  web:
    platform: linux/arm64/v8
    image: alfredo1388/php-sample-web:latest
    container_name: php-sample-web-prod
    ports:
      - "3330:80"
    environment:
      - DB_HOST=db
      - DB_NAME=sample
      - DB_USER=sampleuser
      - DB_PASSWORD=samplepass
    volumes:
      - ./logs:/var/www/html/logs
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    platform: linux/arm64/v8
    image: alfredo1388/php-sample-db:latest
    container_name: php-sample-db-prod
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=sample
      - MYSQL_USER=sampleuser
      - MYSQL_PASSWORD=samplepass
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "sampleuser", "-psamplepass"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db_data:
